name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: Build Executable
      run: pyinstaller --onefile --noconsole src/main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/
